export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";

export const GET_INIT_INFORMATION = "GET_INIT_INFORMATION";
export const GET_MESSAGES_FOR_ACTIVE_CHAT = "GET_MESSAGES_FOR_ACTIVE_CHAT";

export const RECEIVE_NEW_INFO_CHAT = "RECEIVE_NEW_INFO_CHAT";
export const RECEIVE_NEW_MESSAGES_IN_ACTIVE_CHAT = "RECEIVE_NEW_MESSAGES_IN_ACTIVE_CHAT";

export const CHAT_SIGN_OUT = "CHAT_SIGN_OUT";


export const SEND_MESSAGE = "SEND_MESSAGE";
export const DROP_MESSAGE = "DROP_MESSAGE";
export const DROP_CHAT = "DROP_CHAT";
export const MAKE_READ_CHAT = "MAKE_READ_CHAT";

export const ERROR_ON_SERVER = "ERROR_ON_SERVER";
export const ERROR_TYPE = "ERROR_TYPE";