export const LOAD_USERS_FOR_LIKE_SUCCESS = "LOAD_USERS_FOR_LIKE_SUCCESS";
export const LOAD_USERS_FOR_LIKE_FAILED = "LOAD_USERS_FOR_LIKE_FAILED";

export const NEXT_SLIDE = "NEXT_SLIDE";

export const LOAD_MATCHES = "LOAD_MATCHES";

export const SIGN_OUT = "SIGN_OUT";