export const LOG_IN_REQUEST = "LOG_IN_REQUEST";

export const GET_USER_DATA_BY_JWT_SUCCESS = "GET_USER_DATA_BY_JWT_SUCCESS";
export const GET_USER_DATA_BY_JET_FAILED = "GET_USER_DATA_BY_JET_FAILED";

export const EDIT_USER_DATA = "EDIT_USER_DATA";

export const SIGN_OUT = "SIGN_OUT";